### ISSUE TITLE
UI becomes unresponsive on `Open in Git host` when custom GitHub Enterprise URL is configured

### ISSUE THREAD

**Issue by aCandidMind** [ben-gibson/jetbrains-open-in-git-host#20]
We have a GitHub Enterprise instance with a non github.com URL. When using any of your two menu entries the whole UI becomes unresponsive. One can then only switch between different IntelliJU windows using the keyboard, but nothing is clickable. Alt hotkeys for menu entries don't work either. When using `Navigate -> Select In` the popup stays visible after clicking `Open in Git host`. There's nothing printed in the IntelliJ Event Log. The only option is then to kill the IntelliJ IDE. With github.com URLs everything works.

**Comment by ben-gibson** [comment]
Hello,

Thanks for this, as a test could you take a look at the setting you have for **SSH executable** in Preferences → Version Control → Git. If it's 'Built-in' could you try switching it to 'Native' and then trying again and let me know the results.

**Comment by ben-gibson** [comment]
This has been fixed in #21. Version 1.5.5 has now been released with the changes. Could you let me know if it has solved the issue for you.

**Comment by aCandidMind** [comment]
Very nice! At first I thought the bug was still there because initially nothing happened. But then my key pass-phrase was prompted and after I provided it, the plugin opened the proper branch on our non github.com instance.

Thank you very much for the fix and the fast response!

Your plugin is now the only one capable of opening the current branch on a non github.com repo. `Open in GitHub` only works with github.com and is not open source. [Copy & Browse as Github or Atlassian Stash Path](https://github.com/jawspeak/intellij-plugin-copy-and-open-github-url) always opens `master`.
