### ISSUE TITLE
Select target action does not include the line number when used from the editor

### ISSUE THREAD

**Issue by markiewb** [ben-gibson/jetbrains-open-in-git-host#24]
The basic feature 
    ```Select File in Project view, Alt-F1 from editor, invoke "Open in Git Host" ```
works correctly.

But
    ```Open file in editor, place cursor, Alt-F1 from editor, invoke "Open in Git Host"``` -> 
ACTUAL
Browser is opened but without correct line number
EXPECTED
Browser is opened with correct line number

**Comment by markiewb** [comment]
Pull-Request for this issue has been provided by #25

**Comment by ben-gibson** [comment]
Thanks for the PR, I will take a look and try to get this fix released shortly.
